services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/templates:/etc/nginx/templates
      - sock:/sock
    env_file:
      - ./.env

  php-fpm:
    build: ./php/
    container_name: php-fpm
    volumes:
      - ./src/:/var/www/html/
      - sock:/sock
      - ./php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

  redis:
    image: redis:latest
    container_name: redis

volumes:
  sock: